const channelList = [
  {name:"Saudi Quran", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4atGM34rXtNQzx2wCnQQVzGSjU805qIOdFw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/SaudiQuran-142/playlist.m3u8"},
  {name:"Saudi Sunnah", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGupfsMkkP5X3iP6XZx6yi2LSzq8_6TIOC-w&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/SaudiSunnah-141/live/141M/chunks.m3u8"},
  {name:"Madani TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuLdTFn4TdP5-rF7YyPXTvOKguRsWJ0q0-cEDZUJ1gKGIl85TEpTiYSx0&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/Madni-121/playlist.m3u8"},
  {name:"PTV Home", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqsvRHu6ZhAQdM0FE5MRF4Goto2-mcA6K4sw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/ptv-home-174/playlist.m3u8"},
  {name:"Bol TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQIKXUbh96lR2jrQ90lzfteBQuVL8TROFk0w&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/bolnent-159-4/playlist.m3u8"},
  {name:"Bol News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgK3r8pJhDdYfdu-8lGclYbvW6W4wB9lNqF-1MvwY05aPkBrB_1zigQHA&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/bolnews-159-3/playlist.m3u8"},
  {name:"Express News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwagVGRGWczQgdzNC-RdEl1t0eF_C8_yzh-o-9WlBh7yfFR6ovB8AIKi61&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/ExpressNews-155/playlist.m3u8"},
  {name:"Express Ent", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCfJKkUhCHVllOSPBVjwCFpPn9b-P_of0kjA&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/EXP-ENT-159-1/playlist.m3u8"},
  {name:"Jalwa", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnWayKJ8devGcnrbcnfboF1RETCKoWr2aFjP-1W8iw-1p4TlYmZ6bQwnlG&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/JalwaTV-135/live/135M/chunks.m3u8"},
  {name:"8XM", logo:"http://8xm.tv/wp-content/uploads/2019/02/512X512p.png", url:"https://vodzong.mjunoon.tv:8087/streamtest/8XM-131/playlist.m3u8"},
  {name:"Oxygen Tv", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5pVm-0Pp3hKucynZctFMIeh985gMe84RR3A&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/132M/playlist.m3u8"},
  {name:"Geo Tv", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJvGC860EQrod1hNmPrj9gyzoub5Qgg2M0l_12dQS18O914xV-yjE1-zHH&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/geoent-122/playlist.m3u8"},
  {name:"Geo News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTvmQmYYa9mh7dXePN1DEBpawvKb2Jcd0Shw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/geonews-137/playlist.m3u8"},
  {name:"Urdu 1", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpxnA2_kHg8QgWos0GjlvCvENmdUgQhhTO1hIAwqSOE4Txfibg0oCxaq4&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/Urdu1-158-4/playlist.m3u8"},
  {name:"A Plus", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdzutge89wiGQnXi2_-xgth7iKTQiHQS1ZzQ&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/APlus-118/playlist.m3u8"},
   {name:"AAJ Entertainment", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUKeKZG1vzTQk_qslUAkxCz_KwQo4bXdFL7d1OFpH6-XkZNk0&s", url:"https://vodzong.mjunoon.tv:8087/streamtest/AAJENT-125/playlist.m3u8"},
  {name:"AAJ News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw3XifA6zKwga4pcAvvSHEi4Jx-vMLbIBfjBijrZiG1hhVwtxJES73OqXk&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/AAJNews-124/playlist.m3u8"},
  {name:"Sindh TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGsxWjXyJ9Nxvf78Le-W1jkerBBuztBahqs6VO3g8QZPVJC_LKagkmBYU&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/SindhTV-136-1/live/136-1M/chunks.m3u8"},
  {name:"Sindh News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTElWZUWbSKUaT9_4ZMQ_6rH2n7qzcRCsmrgw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/SindhNews-136-2/playlist.m3u8"},
  {name:"KTN TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1Vbtybwih6wSaFraEAU6ym_-jyUXoz9qBYA&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/KTN-149/playlist.m3u8"},
  {name:"KTN News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqACj5a67chU59ADkTM8gApWbYjQjKyDzHEA&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/KTNNews-151/playlist.m3u8"},
  {name:"Kashish TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7a5ORjEqgt5veU6e0ltVmk_IZuov34IVWN4DwQELwboZIEJc&s", url:"https://vodzong.mjunoon.tv:8087/streamtest/Kashish-150/playlist.m3u8"},
  {name:"Awaz TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGw2NFUe2PRUaUZ5zPFexMWsJdD5XdTJhcUg&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/AWAZ-120/playlist.m3u8"},
  {name:"Time News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9ItuK1wSgi8G2Cluif09aNKdbxSYa5E1pYJw66W6RDjck2-KfHIlBAAM&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/time-news-172/playlist.m3u8"},
  {name:"Play TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsltTCnRhJul3X7RgioroIN-fkR6G9nh7z3g&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/playtv-154/playlist.m3u8"},
  {name:"AbbTak News", logo:"https://upload.wikimedia.org/wikipedia/en/c/c3/Abb_Tak_news_logo.png", url:"https://vodzong.mjunoon.tv:8087/streamtest/AbbTakNews-133/live/133H/chunks.m3u8"},
    {name:"Samaa TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxegS2MnXuq9RiMdfxqW8rfqlyFKTr5HwMgg&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/Samaa-157-3/playlist.m3u8"},
  {name:"Dawn News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrs-9thVXyGDeokLLg9jJeGGRtg3P7WdWMzg&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/DawnNews-152/playlist.m3u8"},
  {name:"Hum TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkYgs_Akm-8OaExLxX2Jk1Vm3VKV6zTJake-vDe3Nho7vfL1C2zHFuEDDN&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/Hum-TV-136-3/playlist.m3u8"},
  {name:"Hum News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmsgdiQC-oH_neSmr9rn4Q64tmaPXjW_pCeg&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/Hum-news-80/playlist.m3u8"},
  {name:"Dunya News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTk5mYNrIsFgaQacU64xg6TXvnHdDrhK_s1Tg&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/DunyaNews-113/playlist.m3u8"},
  {name:"See TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZYOj6PnXQCNoA2S1vK79MpuGOP5Y3ow4IA7kwj3yeNqdgrrz9M9l_QEA&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/SeeTV-156/playlist.m3u8"},
  {name:"Baby TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfsji6pOJevIdHmug5J2ppCxB40sBaCEqfqcnNo06Xrzr-uHNvKA6BoEk&s=10", url:"https://vodzong.mjunoon.tv:8087/streamtest/babytv-77/playlist.m3u8"},
  {name:"Champion TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOoWEUxqSt1T1KHUwj-3S_U_TlAZ-JtR1ujQ&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/champion-177/playlist.m3u8"},
  {name:"Movie One", logo:"https://i1.wp.com/tvtonight.com.au/wp-content/uploads/2013-01-01_1835.jpg?w=290&ssl=1", url:"https://vodzong.mjunoon.tv:8087/streamtest/movie-one-176/playlist.m3u8"},
  {name:"TV1", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQN4ty614iusgACZsNv19qUIaOWQfjC_svwTg&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/TV1-129/playlist.m3u8"},
  {name:"WASEB", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6nNDOHnQcTUrc927J8WJCKguprLBriecThA&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/WASEB-130/playlist.m3u8"},
  {name:"Roz News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3HxB_nRvvD0KireVtBymmZD-ZScTmYwQSow&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/RozNews-139/playlist.m3u"},
  {name:"VSH News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZdvN4yiS31fNgC1fv48P-a7IXWi6MIe7yAQ&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/VSHTV-122/playlist.m3u8"},
  {name:"Channel 5", logo:"https://pbs.twimg.com/media/EwAo8HrXMAITpUb?format=jpg&name=360x360", url:"https://vodzong.mjunoon.tv:8087/streamtest/Channel5-159-4/live/159-4M/chunks.m3u8"},
  {name:"DW", logo:"https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Deutsche_Welle_symbol_2012.svg/1200px-Deutsche_Welle_symbol_2012.svg.png", url:"https://vodzong.mjunoon.tv:8087/streamtest/DW-136-4A/playlist.m3u8"},
  {name:"Cartoon Network", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPVRFCHHW_gH-9LSOuxX2zcLYQS3xQVXuTGw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/cartoon-network-87/playlist.m3u8"},
  {name:"Aruj TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTq40dDTWvE6YwjbB3LSdTapLtAbVtdRoLyiw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/ArujTV-117/playlist.m3u8"},
  {name:"A1 News", logo:"https://pbs.twimg.com/profile_images/973580855317708801/0AJ7v7He.jpg", url:"https://vodzong.mjunoon.tv:8087/streamtest/A1-184/playlist.m3u8"},
  {name:"K21 News", logo:"https://pbs.twimg.com/media/EwAp_IFXIAEs3i3?format=jpg&name=240x240", url:"https://vodzong.mjunoon.tv:8087/streamtest/K21News-116/playlist.m3u8"},
  {name:"24 HD", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9P-kqdcLO7biPX520IsodHU9A6LeqXO0F2w&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/24HD-146/playlist.m3u8"},
  {name:"Anim Plan", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF_NuLRli6VMhGWfP4NpFPLWWoiCpz4aasQA&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/anim-plan-179/live/179M/chunks.m3u8"},
  {name:"NEWS1", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWrOWoWUoQhKJrM-fmzeYa4FM_zgMZECXBaw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/NEWS1-128/playlist.m3u8"},
    {name:"Public News", logo:"https://upload.wikimedia.org/wikipedia/commons/9/9a/Public-News-Logo-1.jpg", url:"https://vodzong.mjunoon.tv:8087/streamtest/public-115/playlist.m3u8"},
  {name:"Neo News", logo:"https://upload.wikimedia.org/wikipedia/en/a/a6/Neo_News_logo.jpg", url:"https://vodzong.mjunoon.tv:8087/streamtest/Neo-110/playlist.m3u8"},
  {name:"CNN", logo:"https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/CNN.svg/1200px-CNN.svg.png", url:"https://vodzong.mjunoon.tv:8087/streamtest/cnn-86/playlist.m3u8"},
  {name:"Capital TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6dtEgQit4hjIDU8JUzhfFAhgjiXyG0Dw_Gg&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/capitaltv-111/playlist.m3u8"},
  {name:"Apna Channel", logo:"https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Apna_channel_logo.png/440px-Apna_channel_logo.png", url:"https://vodzong.mjunoon.tv:8087/streamtest/ApnaChannel-134/playlist.m3u8"},
  {name:"UK44", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdvENxFCSQlcJQBw32nlhW1xJHgrwf2DJfWA&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/UK44-145/playlist.m3u8"},
  {name:"PASHTO TV", logo:"https://pbs.twimg.com/media/EwA0kReXMAED5fI?format=jpg&name=240x240", url:"https://vodzong.mjunoon.tv:8087/streamtest/PASHTOTV-119/playlist.m3u8"},
  {name:"PNN News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0kRh-QdxrJrPyMjxZkkazHwFNAkAie9cmTA&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/PNN-185/playlist.m3u8"},
  {name:"Sach TV", logo:"https://pbs.twimg.com/media/EwA1CSFXcAMBFuz?format=jpg&name=360x360", url:"https://vodzong.mjunoon.tv:8087/streamtest/sachtv-183/playlist.m3u8"},
  {name:"GTV", logo:"https://pbs.twimg.com/profile_images/1346771276317085696/N5bjSnvm_400x400.jpg", url:"https://vodzong.mjunoon.tv:8087/streamtest/GTV-186/playlist.m3u8"},
  {name:"Afghan TV", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy2CV0JhL9ixGKo1Uh1ruuJhOPzaXjFMIW1A&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/AfghanTV-140/playlist.m3u8"},
  {name:"Karobar TV", logo:"https://pbs.twimg.com/media/EwA2nl_XMAAA0Qf?format=jpg&name=240x240", url:"https://vodzong.mjunoon.tv:8087/streamtest/karobartv-en/live/karobartv-720p/chunks.m3u8"},
  {name:"AVT Khyber", logo:"https://is5-ssl.mzstatic.com/image/thumb/Purple114/v4/23/19/8b/23198bd9-1aef-6776-249e-c2a88fb4af32/source/512x512bb.jpg", url:"https://vodzong.mjunoon.tv:8087/streamtest/AVTKhyber-114/playlist.m3u8"},
  {name:"Khyber News", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRH7RahHiYlpoPwNbSZjiF6NoDL8ANdwrZ_CQ&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/KhyberNews-160/playlist.m3u8"},
  {name:"City42", logo:"https://pbs.twimg.com/media/EwA5-A6WEAAVeny?format=jpg&name=small", url:"https://vodzong.mjunoon.tv:8087/streamtest/City42-144/playlist.m3u8"},
  {name:"KAY2", logo:"https://pbs.twimg.com/media/EwA6NsEXAAgdcOP?format=png&name=360x360", url:"https://vodzong.mjunoon.tv:8087/streamtest/KAY2-127/playlist.m3u8"},
  {name:"City41", logo:"https://pbs.twimg.com/profile_images/1234423034515279874/9Rrus36m_400x400.jpg", url:"https://vodzong.mjunoon.tv:8087/streamtest/City41-143/playlist.m3u8"},
  {name:"ROHI", logo:"https://yt3.ggpht.com/ytc/AAUvwnh5smgopWMbWiIe7eXDVfXH3a7PYhwUoi9CclvY-Q=s900-c-k-c0x00ffffff-no-rj", url:"https://vodzong.mjunoon.tv:8087/streamtest/ROHI-147/playlist.m3u8"},
  {name:"Filmworld", logo:"https://i.ytimg.com/vi/Ii3DzAnpREs/hqdefault_live.jpg", url:"https://vodzong.mjunoon.tv:8087/streamtest/Filmworld-126/playlist.m3u8"},
  {name:"Hum Masala", logo:"https://pbs.twimg.com/media/EwA7OZJWYAAaYFg?format=jpg&name=240x240", url:"https://vodzong.mjunoon.tv:8087/streamtest/hum-masala-81/playlist.m3u8"},
  {name:"Mashriq", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfyx7RH8sbEmTQVmfPajoCBKDMQj-pVRxJzw&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/mashriq-109/playlist.m3u8"},
  {name:"Hum Sitaray", logo:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQndr4CcgbXrrNs8wNz9j2LPNRftSNImlMlNQ&usqp=CAU", url:"https://vodzong.mjunoon.tv:8087/streamtest/HumSitaray-157-4/playlist.m3u8"},
  {name:"Filmax", logo:"https://www.brandsynario.com/directory/wp-content/uploads/2018/01/a-23.png", url:"https://vodzong.mjunoon.tv:8087/streamtest/filmax-158-1/playlist.m3u8"}
];

const grid = document.getElementById("channelGrid");
channelList.forEach(ch=>{
  const img=document.createElement("img"); img.src=ch.logo; img.alt=ch.name; img.className="channel-logo";
  img.onclick=()=>playChannel(img,ch.name,ch.url);
  grid.appendChild(img);
});
